Prevents sending empty tokens to intercom
deepak786/intercom_flutter pull request #103
Opened 2020-11-08 09:19 UTC by obrunsmann

Referring to issue #102 it's very dangerous that the app fully crashes if the token is nil. I was not able to reproduce, why `getToken()` of Firebase Messaging plugin returns null but when callng `Intercom.sendTokenToIntercom(null)` I was able to reproduce the crash. 

So I suggest adding any check which prevents sending non strings to the native handler. While we are working with dynamic return type, I added an exception. I could also imagine to work with boolean return type while I now preferred not changing the function's signature.

2020-11-17 18:38 UTC, Zazo032 requested changes
Hi @obrunsmann! Overall changes LGTM. Only a few small nits about conditions.

Also, do you think you could add a test that verifies that `sendTokenToIntercom` asserts or throws if calling with a `null` or empty token? Thanks!

2020-11-17 18:38 UTC, Zazo032 commented on lib/intercom_flutter.dart
> +    assert(token?.isNotEmpty == true);
```suggestion
    assert(token != null && token.isNotEmpty);
```

2020-11-17 18:38 UTC, Zazo032 commented on lib/intercom_flutter.dart
> +    }
```suggestion
    // A null or empty token may crash the app
    if (token == null || token?.isEmpty) {
      throw '[intercom_flutter] Push token must not be null or empty.';
    }
```

2021-06-24 19:54 UTC, deepak786 commented
As the plugin is now null safe. So the null token cannot be passed. 
For the empty token, there is already an assertion.
https://github.com/v3rm0n/intercom_flutter/blob/359663fb2e49103b501328a3a8c1bcd6a1adca02/intercom_flutter_platform_interface/lib/method_channel_intercom_flutter.dart#L134

So closing the pull request. 
If you still have an issue, feel free to open a new issue or submit the pull request.
Thanks.

2021-06-24 19:54 UTC, closed without merging