Lang support
deepak786/intercom_flutter pull request #121
Opened 2021-02-22 11:25 UTC by AhmedBeheiri

added language override feature mentioned here https://www.intercom.com/help/en/articles/180-localize-intercom-to-work-with-multiple-languages to support multiple languages based on app locale

2021-02-22 11:37 UTC, Zazo032 requested changes
Thanks @AhmedBeheiri for the PR, this will be a nice addition :)

I left some comments, please have a look.

Also, there seem to be a few conflicts that need to be resolved.

Could you also add or modify an existing test to ensure the `lang` param is being passed properly?

2021-02-22 11:37 UTC, Zazo032 commented on example/.flutter-plugins-dependencies
> +{"info":"This is a generated file; do not edit or check into version control.","plugins":{"ios":[{"name":"intercom_flutter","path":"C:\\\\Users\\\\Sales1\\\\StudioProjects\\\\intercom_flutter\\\\","d
This file shouldn't be checked into version control

2021-02-22 11:37 UTC, Zazo032 commented on example/ios/Flutter/flutter_export_environment.sh
> +# This is a generated file; do not edit or check into version control.
This file shouldn't be checked into version control

2021-02-22 11:37 UTC, Zazo032 commented on lib/intercom_flutter.dart
> +        .invokeMethod('setUserHash', {'userHash': userHash});
Could you revert format changes from this file?

2021-02-22 12:51 UTC, Zazo032 approved these changes
Thanks! Only missing thing now is adding your changes to `CHANGELOG.md` and bump the plugin version on `pubspec.yaml` (2.4.0).

2021-02-22 12:51 UTC, Zazo032 commented on test/intercom_flutter_test.dart
> +        lang: 'en'
```suggestion
        lang: 'en',
```

2021-02-22 13:19 UTC, Zazo032 requested changes
There are still a few conflicts that need to be addressed, I can't merge this PR until they're fixed.

Also, I left some minor nits.

2021-02-22 13:19 UTC, Zazo032 commented on CHANGELOG.md
> +* added language override feature to change language based on app locale
```suggestion
* Added language override feature to `updateUser` method.
```

2021-02-22 13:19 UTC, Zazo032 commented on lib/intercom_flutter.dart
> +      IntercomVisibility visibility) {
Revert formatting change here

2021-02-22 13:19 UTC, Zazo032 commented on lib/intercom_flutter.dart
> +        .invokeMethod('sendTokenToIntercom', {'token': token});
Revert formatting change here

2021-02-22 13:19 UTC, Zazo032 commented on lib/intercom_flutter.dart
> +      Map<String, dynamic> message) async {
Revert formatting change here

2021-02-22 13:33 UTC, Zazo032 commented
There are still conflicts:

![image](https://user-images.githubusercontent.com/2807712/108715220-d64e7e80-751a-11eb-826a-d75c2619a045.png)

2021-02-28 07:28 UTC, AhmedBeheiri commented
> There are still conflicts:
> 
> ![image](https://user-images.githubusercontent.com/2807712/108715220-d64e7e80-751a-11eb-826a-d75c2619a045.png)

please check again now

2021-03-08 11:05 UTC, Zazo032 commented
I still see conflicts with your branch. If you can't fix them, you may want to close this PR, create a new branch from `master`, push your changes again, and then create a new PR

2021-03-08 11:07 UTC, closed without merging