Add `displayTickets` interface
deepak786/intercom_flutter pull request #350
Opened 2023-09-04 15:33 UTC by theVinesh

Intercom introduced tickets space recently. This would setup a public method with which end users will be able to present tickets space.

 - Adds `displayTickets` interface
 - Bumps version

2023-09-05 17:37 UTC, deepak786 requested changes

2023-09-05 17:37 UTC, deepak786 commented on intercom_flutter_platform_interface/CHANGELOG.md
> +## 1.3.2
Add line break after "Changelog"

2023-09-05 17:41 UTC, deepak786 commented on intercom_flutter_platform_interface/lib/intercom_flutter_platform_interface.dart
> +    throw UnimplementedError('displayMessages() has not been implemented.');
"displayTickets()" has not been implemented.

2023-09-05 17:48 UTC, deepak786 commented on intercom_flutter_platform_interface/lib/intercom_flutter_platform_interface.dart
> +  /// To display an Activity with your Messages content.
"Submit, view, and get updates on all of your tickets from one centralized place in the Messenger."

2023-09-05 18:00 UTC, deepak786 approved these changes

2023-09-05 18:06 UTC, deepak786 commented
@theVinesh You can create a new PR about the web implementation and method channel from this branch. I will merge all together.

2023-09-06 11:11 UTC, theVinesh commented
@deepak786 [Web](https://github.com/v3rm0n/intercom_flutter/pull/353) and [Mobile](https://github.com/v3rm0n/intercom_flutter/pull/352) Impls are done.

LMK once this is merged and a new version of `flutter_platform_interface` is published.

2023-09-06 20:26 UTC, merged