#55 - migrate to flutter v2 embedding
deepak786/intercom_flutter pull request #82
Opened 2020-07-09 22:39 UTC by tshedor

Ay, thanks for this plugin. It's been super useful. The team @ Greenbits has been making use of this plugin and we noticed there was an open issue for upgrading to Android embedding.

I haven't seen the `registrar.context() as Application` invocation before, but if it's equivalent to `registrar.activity().getApplication()`, then it's all the same.

2020-09-11 09:00 UTC, w3ggy commented
Any updates?

2020-09-30 10:41 UTC, Zazo032 requested changes
Hi @tshedor! Changes seem to be reasonable following  [the migration guide](https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration). Could you check my review comments, and also bump the version in `pubspec.yaml`, `README.md` and write your changes in `CHANGELOG.md`?

2020-09-30 10:41 UTC, Zazo032 commented on android/src/main/kotlin/io/maido/intercom/IntercomFlutterPlugin.kt
> +      unreadEventChannel.setStreamHandler(IntercomFlutterPlugin()
```suggestion
      unreadEventChannel.setStreamHandler(IntercomFlutterPlugin())
```

Missing closing parenthesis

2020-09-30 10:41 UTC, Zazo032 commented on android/src/main/kotlin/io/maido/intercom/IntercomFlutterPlugin.kt
> +      channel.setMethodCallHandler(IntercomFlutterPlugin()
```suggestion
      channel.setMethodCallHandler(IntercomFlutterPlugin())
```

Missing closing parenthesis

2020-09-30 10:41 UTC, Zazo032 commented on android/src/main/kotlin/io/maido/intercom/IntercomFlutterPlugin.kt
> +    application = binding.activity.getApplication();
```suggestion
    application = binding.activity.getApplication()
```

I think this is not required in Kotlin

2020-10-01 20:20 UTC, tshedor commented
@Zazo032 addressed your comments. Sincere apologies, that was sloppy of me to forget so many closing parens.

2020-10-02 10:22 UTC, Zazo032 commented
> @Zazo032 addressed your comments. Sincere apologies, that was sloppy of me to forget so many closing parens.

Don't worry 👍
Could you add bump version to `2.3.0` and add your changes to `CHANGELOG.md`?

Files:

- https://github.com/v3rm0n/intercom_flutter/blob/master/pubspec.yaml#L4
- https://github.com/v3rm0n/intercom_flutter/blob/master/README.md#L3
- https://github.com/v3rm0n/intercom_flutter/blob/master/CHANGELOG.md

2020-10-02 18:28 UTC, tshedor commented
@Zazo032 bumped and updated

2020-10-20 14:53 UTC, Zazo032 approved these changes
LGTM

2020-10-20 14:53 UTC, merged