Implement sendTokenToIntercom method on iOS side
deepak786/intercom_flutter pull request #88
Opened 2020-09-08 09:58 UTC by indigothm

2020-09-08 10:08 UTC, Zazo032 requested changes
Hi @indigothm! Thanks for the PR. Just a few nits. Also, could you state your changes in `CHANGELOG.md` and add a small test that verifies the method is being called properly? Some examples [here](https://github.com/v3rm0n/intercom_flutter/blob/master/test/intercom_flutter_test.dart).

2020-09-08 10:08 UTC, Zazo032 commented on pubspec.yaml
> +version: 2.2.1+1
This should be `2.2.1`

2020-09-08 10:08 UTC, Zazo032 commented on example/ios/Flutter/Flutter.podspec
> +#
Could you remove this file from the PR?

2020-09-08 10:13 UTC, Zazo032 commented on example/ios/Flutter/.last_build_id
> +0c9059c70654b99fdd937e7ed9a0a0ff
Could you add this file to `gitignore` and remove it from the PR?

2020-09-08 10:14 UTC, indigothm commented
Sure, will do that

2020-09-15 21:30 UTC, acoutts commented
Hi! Any progress on finishing this to get it merged in?

2020-09-15 21:54 UTC, indigothm commented
Hey, got distracted from that task a bit. Will try to push it tomorrow

2020-09-15 22:28 UTC, indigothm commented
@acoutts Good to go. Added the test and removed the extra files

2020-09-15 22:36 UTC, Zazo032 commented
Thanks @indigothm! Changes LGTM, could you document your change on `CHANGELOG.md` too?

2020-09-15 22:48 UTC, indigothm commented
@Zazo032 Done

2020-09-16 10:51 UTC, Zazo032 approved these changes

2020-09-16 10:51 UTC, merged